//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04使用EF进行查询操作
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeInfo
    {
        public int GradeId { get; set; }
        public decimal Grade { get; set; }
        public int StuId { get; set; }
        public int CourseId { get; set; }
    
        public virtual CourseInfo CourseInfo { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
