//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03使用EF进行增删改
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.GradeInfo = new HashSet<GradeInfo>();
        }
    
        public int StuId { get; set; }
        public string StuName { get; set; }
        public Nullable<bool> StuGender { get; set; }
        public string StuPhone { get; set; }
        public string StuEmail { get; set; }
        public int ClassId { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeInfo> GradeInfo { get; set; }
    }
}
